package netgloo.models;

import java.sql.Timestamp;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * An entity User composed by three fields (id, email, name). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "USERS")
public class User {

	// ------------------------
	// PRIVATE FIELDS
	// ------------------------

	// An autogenerated id (unique for each user in the db)
	@Id
	@Column(name = "CUID")
	private String cuid;

	@Column(name = "USER_ID")
	private String userId;

	@Column(name = "CREATED_BY")
	private String createdBy;

	@Column(name = "UPDATED_BY")
	private String updatedBy;

	@Column(name = "CREATE_TIMESTAMP")
	private Timestamp createTimestamp;

	@Column(name = "LAST_UPDATE_TIMESTAMP")
	private Timestamp lastUpdateTimestamp;

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "user")
	private List<UserDSR> userDSRList;

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "user")
	private List<UserDSRError> userDSRErrorList;

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "user")
	private List<UserDSRErrorBackUp> userErrBckUpDSRList;

	public String getCuid() {
		return cuid;
	}

	public void setCuid(String cuid) {
		this.cuid = cuid;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public List<UserDSR> getUserDSRList() {
		return userDSRList;
	}

	public void setUserDSRList(List<UserDSR> userDSRList) {
		this.userDSRList = userDSRList;
	}

	public List<UserDSRError> getUserDSRErrorList() {
		return userDSRErrorList;
	}

	public void setUserDSRErrorList(List<UserDSRError> userDSRErrorList) {
		this.userDSRErrorList = userDSRErrorList;
	}

	public List<UserDSRErrorBackUp> getUserErrBckUpDSRList() {
		return userErrBckUpDSRList;
	}

	public void setUserErrBckUpDSRList(List<UserDSRErrorBackUp> userErrBckUpDSRList) {
		this.userErrBckUpDSRList = userErrBckUpDSRList;
	}

	public Timestamp getCreateTimestamp() {
		return createTimestamp;
	}

	public void setCreateTimestamp(Timestamp createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	public Timestamp getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Timestamp lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}
} // class User
